project_id = "kjfjsgzllpqgmpcqpvuz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[functions.send-notification]
verify_jwt = false

[functions.match-talents-to-job]
verify_jwt = true